#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'

git_bundles = %w[
  ap/vim-css-color
  bkad/CamelCaseMotion
  cakebaker/scss-syntax.vim
  elzr/vim-json
  fatih/vim-go
  kchmck/vim-coffee-script
  keithbsmiley/rspec.vim
  majutsushi/tagbar
  ngmy/vim-rubocop
  othree/javascript-libraries-syntax.vim
  plasticboy/vim-markdown
  saks/Specky
  scrooloose/nerdcommenter
  scrooloose/nerdtree
  scrooloose/syntastic
  slim-template/vim-slim
  tpope/vim-endwise
  tpope/vim-haml
  tpope/vim-rails
  tpope/vim-surround
  vim-airline/vim-airline
  vim-ruby/vim-ruby
  wincent/Command-T
]

git_keep = []

bundles_dir = File.join(File.dirname(__FILE__), 'bundle')

FileUtils.mkdir bundles_dir unless File.exists?(bundles_dir)
FileUtils.cd(bundles_dir)

puts "trashing everything..."
Dir['*'].each {|d| FileUtils.rm_rf d unless git_keep.include?(d) }

puts "fetching plugins..."
git_bundles.each do |plugin|
  url = "git://github.com/#{plugin}"
  dir = url.split('/').last

  puts "  Unpacking #{url} into #{dir}"
  %x{git clone #{url} #{dir}}
  FileUtils.rm_rf File.join(dir, ".git")
end

puts "compiling command-t..."

#environment = 'ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"'
#command_t_path = File.join 'Command-T/ruby/command-t'
#rvm_init_script = 'source $HOME/.zshrc && rvm use 2.0.0'
#command_t_build_script = 'bundle && ruby extconf.rb && make'
#puts %x{zsh -c 'cd #{command_t_path} && #{rvm_init_script} && #{environment} #{command_t_build_script}'}
